# Generated by Django 6.0.6 on 2026-07-12 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='picture',
            field=models.ImageField(blank=True, upload_to='buildings/'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='picture',
            field=models.ImageField(blank=True, upload_to='floors/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='picture',
            field=models.ImageField(blank=True, upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=models.ImageField(blank=True, upload_to='rooms/'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dateandtime', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pages2.room')),
            ],
        ),
    ]
