# Generated by Django 6.0.6 on 2026-07-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages2', '0002_alter_building_picture_alter_floor_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
