# Generated by Django 6.0.6 on 2026-07-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages2', '0003_event_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dateandtime',
            new_name='date_and_time',
        ),
    ]
