# Generated by Django 6.0.6 on 2026-07-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages2', '0003_event_organizer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dateandtime',
            new_name='date_and_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(default='2026-07-12'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(default='08:46:00'),
        ),
        
    ]