# Generated by Django 5.2.15 on 2026-07-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages2', '0006_event_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
