# Generated by Django 5.2.15 on 2026-07-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages2', '0007_event_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
    ]
